### ISSUE TITLE
Unable to load serlio.mll in Maya 2022

### ISSUE THREAD

**Issue by reinmain** [Esri/serlio#143]
Trying to manually load serlio.mll from plugin manager gives this error:
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: The specified module could not be found.
 (serlio) //

**Comment by mistafunk** [comment]
my guess: as serlio.mll depends on com.esri.prt.core.dll of PRT you need to make sure that the corresponding directory (plug-ins) of your serlio installation is in the %PATH%

recommended way is to use Maya.env, see https://github.com/Esri/serlio/blob/main/doc/usage.md#windows-compile-from-source

**Comment by mistafunk** [comment]
We just released version 2.0, please try again!
Feel free to reopen if this is still a problem!
