### ISSUE TITLE
Rule Package: @Enum: First Element Fixed to Default Value

### ISSUE THREAD

**Issue by cetfuchs** [Esri/serlio#23]
Repro
1. Create an RPK using @Enum attributes 
`@Enum( "Airplane", "Box", "Train" )`
`attr asset = "Train"`
1. Assign the Rule Package [insertAsset.zip](https://github.com/Esri/serlio/files/3575553/insertAsset.zip) in Maya
1. Select asset "Airplane"
BUG: The default asset "Train" is loaded. 
![image](https://user-images.githubusercontent.com/49071344/64273347-640e6680-cf41-11e9-878d-3d056d654c66.png)

**Comment by mistafunk** [comment]
fixed for 1.2 (internal ticket CE-9150)
