### ISSUE TITLE
Maya nodes provided by the plugin need to use an ID registered with Autodesk

### ISSUE THREAD

**Issue by jonathan-meier** [Esri/serlio#26]
Tasks:
* register an ID block with Autodesk (see http://mayaid.herokuapp.com/)
* use the ID block to assign node IDs to all nodes (currently `PRTModifierNode`, `PRTMaterialNode` and `ArnoldMaterialNode`) defined by the plugin (see [`MTypeId` doc](https://help.autodesk.com/view/MAYAUL/2019/ENU/?guid=Maya_SDK_MERGED_cpp_ref_class_m_type_id_html))

**Comment by mistafunk** [comment]
filed as internal ticket CE-7193

**Comment by mistafunk** [comment]
PR #47

**Comment by mistafunk** [comment]
merged & verified
