### ISSUE TITLE
Arnold: adding light sources

### ISSUE THREAD

**Issue by jonathan-meier** [Esri/serlio#28]
In a newly created Maya scene, there are no light sources added by default. Therefore, we always add a physical sky light source to the scene, when we attach Arnold materials to a PRT model, since without a light source Arnold just renders black. However, if there are already existing light sources in the scene, this might not be desirable.

Task:
* Decide on a reasonable strategy for automatically adding light sources and implement it.

**Comment by mistafunk** [comment]
imho, we should not be smart and try to add lights if there are none - might easily interfere with users workflows.

**Comment by mistafunk** [comment]
closing this without taking action
