### ISSUE TITLE
Improve matching of existing material shader to the corresponding shading group

### ISSUE THREAD

**Issue by jonathan-meier** [Esri/serlio#29]
Currently, in both `PRTMaterialNode` and `ArnoldMaterialNode` finding the shading group corresponding to a material shader is implemented by simply changing a known infix in the node name. E.g. a shader node with the name `serlioGeneratedArnoldMaterialSh7` will match to the shading group with the name `serlioGeneratedArnoldMaterialSg7`. However, this method is unreliable, since nodes can be renamed by the user.

Task:
* Find a more reliable way to match a shader with its shading group, e.g. by inspecting the attribute connections, since the `.outColor` attribute of a shader is connected to the `.surfaceShader` attribute of the corresponding shading group.

**Comment by mistafunk** [comment]
probably redundant after #40

**Comment by jonathan-meier** [comment]
It is not an issue for `ArnoldMaterialNode` anymore, since we now attach material metadata for arnold materials directly to the shading group. It is still an issue for `PRTMaterialNode` though, which essentially needs a refactoring based on the improvements in `ArnoldMaterialNode`.

**Comment by mistafunk** [comment]
This has been done within #40.
