### ISSUE TITLE
Arnold: material deduplication

### ISSUE THREAD

**Issue by jonathan-meier** [Esri/serlio#40]
Currently, when setting up the Arnold material shaders for a model, we don't consider already existing and matching material shader from other models and instantiate a new material shader in any case. Even worse, when changing model attributes and regenerating the model and materials, the material shaders from before the change are ignored and all material shaders are newly created.

Task:
* Implement material shader reuse across all models and model regenerations.

Note: for the viewport material we already have deduplication

**Comment by mistafunk** [comment]
internal ticket CE-7285

**Comment by mistafunk** [comment]
TODO:
* encapsulate naming of arnold shading group and surface shader
* address remaining TODOs in code comments

**Comment by cetfuchs** [comment]
serlio-1.0.1+b3005.maya2019.prt2-1-5705-windows
Functional Review: Passed

When changing CGA parameters:
- [x] no duplicate Arnold materials are generated
- [x] additional Arnold materials are generated when needed
- [x] unused Arnold materials are not deleted and get re-used
