### ISSUE TITLE
Unique shader names

### ISSUE THREAD

**Issue by jonathan-meier** [Esri/serlio#41]
For our material shaders (both Arnold and viewport materials), we currently use a fragile approach of marking our nodes as sequential (so that their compute method doesn't get executed in parallel to other node's compute method) as well as sequentially executing MEL scripts to ensure that the shader names of our material shaders are unique. This is not necessary, since Maya itself already ensures uniqueness of node names.

Task:
* Adapt our material nodes to rely on Maya's unique node name assignment instead of trying to ensure uniqueness ourselves.

**Comment by mistafunk** [comment]
this has been done within #40
