### ISSUE TITLE
Consistent default attribute handling

### ISSUE THREAD

**Issue by jonathan-meier** [Esri/serlio#50]
In CityEngine, a rule attribute can be in two states, namely in default mode or in override mode.

In default mode, the attribute always assumes the default value that is computed by the rule. The default value may change depending on the value of other attributes, the seed or the geometry.

In override mode, the user sets the attribute value explicitly, thereby overriding the default value. The attribute value always assumes the user set value, even if the default value changes when the value of other attributes, the seed or the geometry is altered.

Currently, in serlio all attributes are always treated as if they were in override mode. The attribute default values are computed once when a rule is assigned to a shape and used as the "user set" values for the override mode. A user who wishes to mimic the default mode has to manually compute and set default values if they differ from the default values computed initially. There is also no way to reset an attribute value to its current default value.

Task:
* Implement the behavior of default and override mode for attributes in serlio according to the behavior of CityEngine described above.
* Provide a way for the user to reset attribute values to their default in the UI.

Note:
* Hidden boolean plugs might be a possibility to indicate the attribute modes.
* Issue #49 is **not** covered by this issue and should probably be fixed first.

**Comment by mistafunk** [comment]
internal tickets CE-6848 and CE-6856
