### ISSUE TITLE
Consistent seed handling

### ISSUE THREAD

**Issue by jonathan-meier** [Esri/serlio#51]
In CityEngine, we compute a random seed for a shape once based on its geometry. After that, the user can freely change the seed, but there is no way to reset the seed to its initial value implicitly (i.e. you have to explicitly remember the initial seed and manually set it to achieve a reset).

Essentially, the seed is an attribute that is always in override mode (as described in #50) and initialized to a random seed.

In serlio, we are not consistent, but use different seeds to compute the default attribute values and generate models. As far as I could see, the random seed for generating the models even relies on uninitialized memory (i.e. it just uses whatever value is returned from an uninitialized plug).

Task:
* Ensure that the seeds for both default attribute computation and model generation are always the same.
* Make the behavior of the seed consistent with CityEngine.

**Comment by mistafunk** [comment]
Internal ticket CE-7381

**Comment by mistafunk** [comment]
Fixed in v2.0
