### ISSUE TITLE
File type annotation results in wrong file filter

### ISSUE THREAD

**Issue by cetfuchs** [Esri/serlio#55]
Repro

1. Mark an attribute as a file name. 
Example:
```
@File
attr test0300File = "myfile.obj"
```
2. The Serlio inspector will present a file chooser.
<img width="202" alt="2019-11-12_12-59-29" src="https://user-images.githubusercontent.com/49071344/68670096-592d0f00-054c-11ea-9208-317503eed276.png">
3. Try to select another file
BUG: File Type Restriction Set to Attribute Name
<img width="327" alt="2019-11-12_12-51-45" src="https://user-images.githubusercontent.com/49071344/68670132-76fa7400-054c-11ea-8de4-1378d195b824.png">

**Comment by mistafunk** [comment]
Internal ticket CE-7383

**Comment by mistafunk** [comment]
Fixed in v2.0
