### ISSUE TITLE
Serlio fails to load at Maya startup

### ISSUE THREAD

**Issue by mistafunk** [Esri/serlio#63]
serlio.mll fails to load at Maya (2019) startup with error message:
```
// Error: Serlio: the required dependency 'shaderFXPlugin' is not loaded, please activate it! // 
// Error: line 1: initializePlugin function failed (serlio) // 
// Error: line 1: Invalid object or value: // 
// Error: line 1: Invalid object or value: // 
```
Manually activating the plugin works.

**Comment by mistafunk** [comment]
Problem: Maya tries to load serlio before shaderFXPlugin.

Manual workaround:
1. Start Maya and manually load serlio, activate auto-load
1. Ensure that in Windows->Settings/Preferences->Preferences->Save Actions the checkbox "Save all preferences and settings when Maya exits" is enabled
1. Exit Maya
1. Edit the file $HOME/maya/2019/prefs/pluginPrefs.mel and move the line containing serlio to the end of the file

**Comment by mistafunk** [comment]
Fixed by not checking for shaderFXPlugin (or generally for dependencies) at initialization phase because the Maya plugin load order is for all practical purposes undefined. We now only do one check at the very first run of material node ::compute.

**Comment by cetfuchs** [comment]
Fixed: PRT (Serlio) now loads at startup of Maya

**Comment by cetfuchs** [comment]
Fixed: PRT (Serlio) now loads at startup of Maya
